/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./app/**/*.{js,vue,ts}",
    "./components/**/*.{js,vue,ts}",
    "./layouts/**/*.vue",
    "./pages/**/*.vue",
    "./plugins/**/*.{js,ts}",
    "./app.vue",
    "./error.vue"
  ],
  theme: {
    extend: {
      colors: {
        surface: '#121414',
        'surface-dim': '#121414',
        'surface-bright': '#38393a',
        'surface-container-lowest': '#0d0e0f',
        'surface-container-low': '#1a1c1c',
        'surface-container': '#1e2020',
        'surface-container-high': '#292a2a',
        'surface-container-highest': '#343535',
        'on-surface': '#e3e2e2',
        'on-surface-variant': '#c3c9b2',
        'inverse-surface': '#e3e2e2',
        'inverse-on-surface': '#2f3131',
        outline: '#8d937e',
        'outline-variant': '#434938',
        'surface-tint': '#a4d64c',
        primary: '#fefff1',
        'on-primary': '#233600',
        'primary-container': '#bef264',
        'on-primary-container': '#4b6e00',
        'inverse-primary': '#476800',
        secondary: '#c8c6c5',
        'on-secondary': '#303030',
        'secondary-container': '#474746',
        'on-secondary-container': '#b7b5b4',
        tertiary: '#fcffff',
        'on-tertiary': '#313030',
        'tertiary-container': '#e4e1e0',
        'on-tertiary-container': '#646363',
        error: '#ffb4ab',
        'on-error': '#690005',
        'error-container': '#93000a',
        'on-error-container': '#ffdad6',
        'primary-fixed': '#bff365',
        'primary-fixed-dim': '#a4d64c',
        'on-primary-fixed': '#131f00',
        'on-primary-fixed-variant': '#354e00',
        'secondary-fixed': '#e4e2e1',
        'secondary-fixed-dim': '#c8c6c5',
        'on-secondary-fixed': '#1b1c1c',
        'on-secondary-fixed-variant': '#474746',
        'tertiary-fixed': '#e5e2e1',
        'tertiary-fixed-dim': '#c8c6c5',
        'on-tertiary-fixed': '#1c1b1b',
        'on-tertiary-fixed-variant': '#474746',
        background: '#121414',
        'on-background': '#e3e2e2',
        'surface-variant': '#343535',
        
        // Abstract layers mapped to DESIGN.md intent
        'layer-0': '#0A0A0A',
        'layer-1': '#171717',
        'layer-2': '#262626',
        accent: '#BEF264',
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
        heading: ['Hanken Grotesk', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
      }
    },
  },
  plugins: [],
}
