"""Add ClientMember table

Revision ID: 6327211c72da
Revises: 1f4b00c456ea
Create Date: 2026-06-05 18:07:33.785659

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6327211c72da'
down_revision: Union[str, Sequence[str], None] = '1f4b00c456ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_members',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('member_token', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('client_members', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_client_members_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_client_members_member_token'), ['member_token'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client_members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_client_members_member_token'))
        batch_op.drop_index(batch_op.f('ix_client_members_client_id'))

    op.drop_table('client_members')
    # ### end Alembic commands ###
