"""Add client_member_id to sessions

Revision ID: 81722403a1ef
Revises: 6327211c72da
Create Date: 2026-06-05 18:09:13.070117

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81722403a1ef'
down_revision: Union[str, Sequence[str], None] = '6327211c72da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('client_member_id', sa.Uuid(), nullable=True))
        batch_op.create_index(batch_op.f('ix_client_sessions_client_member_id'), ['client_member_id'], unique=False)
        batch_op.create_foreign_key('fk_client_sessions_client_member_id_client_members', 'client_members', ['client_member_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client_sessions', schema=None) as batch_op:
        batch_op.drop_constraint('fk_client_sessions_client_member_id_client_members', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_client_sessions_client_member_id'))
        batch_op.drop_column('client_member_id')

    # ### end Alembic commands ###
