"""Add notifications and update users clients

Revision ID: e7afc25e3448
Revises: a3cfda53313d
Create Date: 2026-06-08 15:52:10.732093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7afc25e3448'
down_revision: Union[str, Sequence[str], None] = 'a3cfda53313d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notification_email_prefs', sa.JSON(), server_default='{}', nullable=False))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notification_email_prefs', sa.JSON(), server_default='{}', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('notification_email_prefs')

    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_column('notification_email_prefs')

    # ### end Alembic commands ###
